# Generated by Django 4.2.17 on 2024-12-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_game_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='buyer',
            field=models.ManyToManyField(related_name='game', to='task1.buyer'),
        ),
    ]
